# Generated by Django 5.0.3 on 2024-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=None, max_length=50, verbose_name='slug'),
        ),
    ]
