# Generated by Django 5.0.3 on 2024-03-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_delete_tryout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='updated_at',
        ),
    ]
