# Generated by Django 5.0.3 on 2024-03-30 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_delete_tryout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Дата производства'),
        ),
    ]
